spring:
  datasource:
    test:
      url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=UTF8
      username: root
      password: yushachen
      driver-class-name: com.mysql.jdbc.Driver
      druid:
        min-idle: 1
        max-active: 300
        filter:
          stat:
            log-slow-sql: true
            slow-sql-millis: 50
        initial-size: 1
        max-wait: 60000
        validation-query: select 1
        test-while-idle: true
